flight:
  outbound_date: "2026-09-25"
  return_date: "2026-10-07"
  departure_airports:
    - code: SHA
      city: "上海"
    - code: PVG
      city: "上海"
    - code: HGH
      city: "杭州"
    - code: NKG
      city: "南京"
    - code: WUX
      city: "无锡"
    - code: CZX
      city: "常州"
    - code: NTG
      city: "南通"
  arrival_airport:
    code: URC
    city: "乌鲁木齐"
  return_airports:
    - code: SHA
      city: "上海"
    - code: PVG
      city: "上海"
    - code: HGH
      city: "杭州"
    - code: NKG
      city: "南京"
    - code: WUX
      city: "无锡"
    - code: CZX
      city: "常州"
    - code: NTG
      city: "南通"

schedule:
  interval_hours: 6

notification:
  feishu:
    app_id: "cli_a94a1e6c05b89bd8"
    app_secret: "dq13MLrIrGBaKOjmQVtwLeGV3NKW44EY"
    chat_id: "oc_f30e25cceed2f9d385725a7b34aedd28"
  price_drop_threshold: 200

anti_detect:
  min_delay: 15
  max_delay: 30
  proxy: null

database:
  path: "data/flights.db"
